### ISSUE TITLE
Why to use DataType.Email for setting the InputType=Email for Textbox when an Textbox can easily accepts Email Address

### ISSUE THREAD

**Issue by AnmolRathod1** [jongalloway/MVA-Introduction-to-ASPNET-MVC#5]
I refered to the ASP.net MVC tutorial Series On MVA and i got stuck on one point that why i should use or specify DataType.Email in model just for setting the Type of textBox to Email this thing can be done without affecting the Model class file.? and infect setting the Data Type of the attribute of Model class as string it would easily accept the Email ID as a whole string. So please Clear out this Doubt Thanks in Advance.

**Comment by ghost** [comment]
You are definitely right, you could use it without the given attribute. However, if you want to have data validation out of the box, you would want to include that as well.

**Comment by LordScree** [comment]
Hi AnmolRathod1. You are right in that, without the email attribute, input fields will accept email data. However, you could think of it in terms of sets: email input is a _subset_ of general text input. If you know you are collecting just email type data, you would want to narrow the focus. If you are looking for any text input, including email, you would want to leave the attribute off.

One analogy is with fruit, where apple is a subset of fruit:
"I would like a piece of fruit": You could get a banana, an orange, an apple, a pears, etc.
"I would like an apple:" You just get an apple.

It's also worth noting that modern browsers make use of the additional HTML attributes rendered on the page. So you're not just getting the benefit of email validation, but you may also get a more email-focussed on-screen keyboard and other UI benefits when you use the email attribute. Think specifically with tablet PCs and smart phones, where the keyboard is shown on the screen; an email-focussed keyboard may include common domain-name endings (such as .com, .org, etc.) and a prominent "@" symbol.

Finally, you can create your own attributes to do other validation or provide you with client-side hooks for certain fields. If you get into the habit of using the right built-in attributes for the right fields, you will be more likely to add new custom functionality in _the Microsoft MVC way_, which will make your code more readily usable by others and probably make it easier to develop in the first place.

I hope that helps.

**Comment by AnmolRathod1** [comment]
@LordScree thank you for your help you explained me in much much easier way and yes it helped me a lot
